### ISSUE TITLE
DynamicSingleTextField expands and causes the widgets below it to be pushed to the bottom

### ISSUE THREAD

**Issue by hossam1244** [NicosNicolaou16/dynamic_single_text_field#4]
**Issue description:** 
 the DynamicSingleTextField expands and causes the widgets below it to be pushed to the bottom

![Simulator Screenshot - iPhone 15 Pro - 2024-07-28 at 21 48 09](https://github.com/user-attachments/assets/0cded494-4300-4da1-aa18-7eec9465f49c)

**Comment by NicosNicolaou16** [comment]
The issue has be fixed and you have the option to set the height of the `ListView` (default value for the height is 150), added an option `singleDynamicListHeight`. The fixed will included on version 0.0.3.
@hossam1244 thank you very much for you feedback!
