### ISSUE TITLE
Suggestion for adding on-complete-submit button 

### ISSUE THREAD

**Issue by hossam1244** [NicosNicolaou16/dynamic_single_text_field#5]
@NicosNicolaou16 Thank you for the library! I would suggest adding an on-submit button to the dynamic text field to help capture the full input once the user finishes typing.

**Comment by NicosNicolaou16** [comment]
@hossam1244 thank you very much for finding the package useful! I have the option for submitting when the user finished the typing, the option is `onSubmitSingleText`.
I improved the documentation and example, you can find example on version 0.0.3.
